### ISSUE TITLE
Autocomplete does not include upper case characters

### ISSUE THREAD

**Issue by argarak** [yuutayamada/company-arduino#1]
As I start to type a function or variable name, the autocomplete comes up with the correct variable/function name, the only difference is that it has no upper case characters - _which is quite important_.

![company-arduino](https://cloud.githubusercontent.com/assets/13645600/11666230/62df71d4-9de3-11e5-9d36-f1a98364f1d2.png)

I personally cannot find the cause of this problem, as looking at the source of this project and arduino-mode gave me nothing (I have also not made anything in Lisp before). 

C, C++ and irony modes work fine with Company.

I am using Emacs 24.5 on GNU/Linux.

**Comment by yuutayamada** [comment]
Sorry for late reply. (somehow I lost the notification)
After I updated company-mode, company-irony, and company-c-headers,
I could auto-complete with upper cased function names.

I forgot to make sure the auto-completion before I update and 
I'm using master branch of Emacs.
Hope this help you.

I'm also afraid that you showed me other completion result (like `company-dabbrev`).
Could you try `M-x company-irony` and give me the result?
If company-arduino work correctly, you should see function name and type information.
(for example: `digitalWrite(int uint8_t, int)` when you do M-x company-irony after `dig`)

**Comment by argarak** [comment]
In `arduino-mode`, `company-irony`, after running `irony-mode`, outputs `Cannot complete at point`, which means that company-irony is somehow _incompatible_ with `arduino-mode`? 

I could get correct autocompletion when I ran `c-mode` and then `irony-mode`. (Without argument types shown)

I think it's just `company-irony` not playing nicely with `arduino-mode`.

**Comment by yuutayamada** [comment]
Although I'm changing the company-mode's color, the below picture is what I see
when I did M-x company-irony.

![company_arduino](https://cloud.githubusercontent.com/assets/1082473/13763921/53a7fe32-ea07-11e5-815e-a542d226df98.png)

**Comment by yuutayamada** [comment]
Does your testing directory match `company-arduino-sketch-directory-regex`?
You can only use company-arduino.el the directory, which match the regex.
(recently I enabled company-arduino if the buffer is arduino-mode too)

**Comment by yuutayamada** [comment]
> In arduino-mode, company-irony, after running irony-mode, outputs Cannot complete at point, which means that company-irony is somehow incompatible with arduino-mode? 

I assume yes, but not sure the true reason...
You may fix by:
- do `(require 'company-arduino)` before you load irony.el because
  company-arduino adds some variables of irony.el.
- remove .elc files if you have old byte compiled files
- check your configured variables if you set correctly

Sorry, I didn't much help...

**Comment by argarak** [comment]
Sorry for keeping this up for so long, but I'm currently not doing any Arduino development and I know this is not your problem, as I have experienced it in `web-mode`, for example.

I'm closing this issue as it relates to my incorrect configuration and not your company-arduino program, and I do not expect anyone finding this useful other than me.

I'll fix it some other day.
