### ISSUE TITLE
use company-irony-c-headers to replace company-c-headers?

### ISSUE THREAD

**Issue by stardiviner** [yuutayamada/company-arduino#3]
Is it possible to use `company-irony-c-headers` to replace `company-c-headers`?

**Comment by yuutayamada** [comment]
maybe yes. It's possible. I haven't tried yet, but I seem you need to
change some variables inside company-arduino.el (see `defvar`s in the file)
if you want to replace. And configure for company-irony-c-headers?

Out of curiosity, is it worth than company-c-headers?

**Comment by stardiviner** [comment]
Because `company-irony-c-headers` works, and `ocmpany-c-headers` does not work on my Emacs.

**Comment by stardiviner** [comment]
I checked company-irony-c-headers, seems not possible to implement custom include headers path feature.
